### ISSUE TITLE
关于数据集答案

### ISSUE THREAD

**Issue by yunfan42** [BUAADreamer/EasyRAG#1]
请问现在AIOPS数据集开源答案了吗？
能否支持一些方法的评测

**Comment by BUAADreamer** [comment]
可以参考这里：https://www.modelscope.cn/datasets/issaccv/aiops24-finals

里面的debug.jsonl也就是本项目main.py中的val集 https://github.com/BUAADreamer/EasyRAG/blob/master/src/data/val.json

我们对val集进行了人工标注从而可以评估关键词准确度

其他的集合暂未公布，可以关注官网

**Comment by BUAADreamer** [comment]
main中把split设置为val即可跑val集测试，可供参考

![image](https://github.com/user-attachments/assets/d754367e-106c-4f49-b722-8f4db8d46ddc)
