### ISSUE TITLE
关于项目中使用HyDE的问题？

### ISSUE THREAD

**Issue by Und3r1ine** [BUAADreamer/EasyRAG#2]
根据论文所说，EasyRAG中使用到了查询扩展和假设文档嵌入（HyDE），请问这两部分的实现代码在什么位置？谢谢。

**Comment by BUAADreamer** [comment]
您好，谢谢您的关注！现在代码里确实缺少这一块内容，我们会尽快补齐！！

顺便解释一下，我们做实验验证了查询扩展和HyDE的效果，但是发现对比赛题目帮助不大，只是对于实际场景可能有帮助

**Comment by Und3r1ine** [comment]
好的，谢谢回复
