### ISSUE TITLE
请问哪部分代码是关于技术报告中Query Expansion的逻辑

### ISSUE THREAD

**Issue by Yuan-Kivi** [BUAADreamer/EasyRAG#6]
我在阅读您团队的技术报告时，对Query Expansion这个机制很感兴趣。但是在代码中好像没有找到相关的部分？

**Comment by BUAADreamer** [comment]
可以参考这里：

https://github.com/BUAADreamer/EasyRAG/blob/51964f57029ab0bc1a581303c2af33eec100748d/src/easyrag/pipeline/pipeline.py#L83
