### ISSUE TITLE
作者您好，可以请问一下您知识路径和文件路径的在您方案中的作用吗，不太懂它们是怎么运用的，感谢您！

### ISSUE THREAD

**Issue by klayc-gzl** [BUAADreamer/EasyRAG#8]

**Comment by BUAADreamer** [comment]
主要是在粗排和重排时将路径和文档块拼接来计算相似度，具体可以参考下图中描述，更多细节可以看看知乎博客：https://zhuanlan.zhihu.com/p/7272025344

![image](https://github.com/user-attachments/assets/639643a5-dad9-4c3f-8f84-aed5e4ea405e)

**Comment by BUAADreamer** [comment]
总的来说我们发现这样做可以将结构化知识注入检索阶段，提升各个环节的准确度

**Comment by klayc-gzl** [comment]
好的，谢谢您
